sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=coverage
install:
  - pip install tox pip setuptools wheel --upgrade
  - if [ "$TOXENV" = "coverage" ]; then pip install coveralls; fi
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - tox
after_success:
  - if [ "$TOXENV" = "coverage" ]; then coveralls; fi
